server:
  port: 9988

logging:
  level:
    root: info
    com.smart: debug

spring:
  application:
    name: smart-sample-2

  config: #导入模块配置文件,支持多模块逗号分隔
    import: optional:classpath:module1/

  messages: #国际化文件目录,支持多模块逗号分隔
    basename: i18n/messages,module1/i18n/messages

  datasource: #数据库连接(可选，统一使用动态数据源方式)
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/smart_sample?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      filters: stat,slf4j
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

#  cloud:
#    nacos:
#      discovery:
#        enabled: true
#        server-addr: 127.0.0.1:8848

smart:
  swagger: #swagger配置信息
    enable: true
    base-packages: com.smart.sample.module1.server.controller #路径扫描,支持逗号分隔，不支持*模糊匹配
    title: smart-sample
    description: smart-sample描述
    version: 2.0.0-SNAPSHOT
    license:
    licenseUrl:
    terms-of-service-url:
    contact:
      name: smart
      email:
      url: